
export const GET_ACCORDION_CATEGORIES ='GET_ACCORDION_CATEGORIES'
export const GET_ACCORDION_CATEGORIES_SUCCESS ='GET_ACCORDION_CATEGORIES_SUCCESS'
export const GET_ACCORDION_CATEGORIES_FAIL ='GET_ACCORDION_CATEGORIES_FAIL'
export const GET_CATEGORY_TREE = 'GET_CATEGORY_TREE';
export const GET_CATEGORY_TREE_SUCCESS = 'GET_CATEGORY_TREE_SUCCESS';
export const GET_CATEGORY_TREE_FAIL = 'GET_CATEGORY_TREE_FAIL';
export const GET_ALL_CATEGORIES_WITH_POSTS = 'GET_ALL_CATEGORIES_WITH_POSTS';
export const GET_ALL_CATEGORIES_WITH_POSTS_SUCCESS = 'GET_ALL_CATEGORIES_WITH_POSTS_SUCCESS';
export const GET_ALL_CATEGORIES_WITH_POSTS_FAIL = 'GET_ALL_CATEGORIES_WITH_POSTS_FAIL';

//fileter option
export const GET_FILTER_OPTIONS = 'GET_FILTER_OPTIONS';
export const GET_FILTER_OPTIONS_SUCCESS = 'GET_FILTER_OPTIONS_SUCCESS';
export const GET_FILTER_OPTIONS_FAIL = 'GET_FILTER_OPTIONS_FAIL';

export const CATEGORY_POSTS_SUCCESS = 'CATEGORY_POSTS_SUCCESS';
 
// CONSTANTES PARA CATEGORY PAGE (Posts filtrados por categoría)
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const GET_CATEGORY_POSTS_SUCCESS = 'GET_CATEGORY_POSTS_SUCCESS';
export const GET_CATEGORY_POSTS_FAIL = 'GET_CATEGORY_POSTS_FAIL';

// CONSTANTES PARA SLIDER DINÁMICO
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_SUBCATEGORY = 'SET_ACTIVE_SUBCATEGORY';
export const SET_ACTIVE_ARTICLE = 'SET_ACTIVE_ARTICLE';

// CONSTANTES PARA SCROLL INFINITO
export const LOAD_MORE_CATEGORIES = 'LOAD_MORE_CATEGORIES';
export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS';

// CONSTANTES DE ESTADO
export const LOADING = 'LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


// redux/constants/categoryConstants.js
 
export const GET_MAIN_CATEGORIES = 'GET_MAIN_CATEGORIES';
export const GET_HIERARCHICAL_CATEGORIES = 'GET_HIERARCHICAL_CATEGORIES';
 