// 📂 redux/constants/categoryConstants.js

// ==================== TIPOS PARA LOADING ====================
export const LOADING = 'LOADING';
export const LOADING_HOME = 'LOADING_HOME';
export const LOADING_CATEGORIES_ACCORDION = 'LOADING_CATEGORIES_ACCORDION';

// ==================== TIPOS PARA HOME (CATEGORÍAS PRINCIPALES) ====================
export const GET_ALL_CATEGORIES_WITH_POSTS = 'GET_ALL_CATEGORIES_WITH_POSTS';
export const GET_ALL_CATEGORIES_WITH_POSTS_SUCCESS = 'GET_ALL_CATEGORIES_WITH_POSTS_SUCCESS';
export const GET_ALL_CATEGORIES_WITH_POSTS_FAIL = 'GET_ALL_CATEGORIES_WITH_POSTS_FAIL';

export const GET_ALL_CATEGORIES_WITHOUT_POSTS = 'GET_ALL_CATEGORIES_WITHOUT_POSTS';
export const GET_ALL_CATEGORIES_WITHOUT_POSTS_SUCCESS = 'GET_ALL_CATEGORIES_WITHOUT_POSTS_SUCCESS';
export const GET_ALL_CATEGORIES_WITHOUT_POSTS_FAIL = 'GET_ALL_CATEGORIES_WITHOUT_POSTS_FAIL';

export const LOAD_MORE_CATEGORIES = 'LOAD_MORE_CATEGORIES';

// ==================== TIPOS PARA ACCORDION (JERARQUÍA) ====================
export const GET_ACCORDION_CATEGORIES = 'GET_ACCORDION_CATEGORIES';
export const GET_ACCORDION_CATEGORIES_SUCCESS = 'GET_ACCORDION_CATEGORIES_SUCCESS';
export const GET_ACCORDION_CATEGORIES_FAIL = 'GET_ACCORDION_CATEGORIES_FAIL';

// ALIAS PARA COMPATIBILIDAD
export const GET_CATEGORIES_FOR_ACCORDION = GET_ACCORDION_CATEGORIES;
export const GET_CATEGORIES_FOR_ACCORDION_SUCCESS = GET_ACCORDION_CATEGORIES_SUCCESS;
export const GET_CATEGORIES_FOR_ACCORDION_FAIL = GET_ACCORDION_CATEGORIES_FAIL;

// ==================== TIPOS PARA CATEGORY PAGE ====================
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const GET_CATEGORY_POSTS_SUCCESS = 'GET_CATEGORY_POSTS_SUCCESS';
export const GET_CATEGORY_POSTS_FAIL = 'GET_CATEGORY_POSTS_FAIL';

export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS';

export const GET_CATEGORY_TREE = 'GET_CATEGORY_TREE';
export const GET_CATEGORY_TREE_SUCCESS = 'GET_CATEGORY_TREE_SUCCESS';
export const GET_CATEGORY_TREE_FAIL = 'GET_CATEGORY_TREE_FAIL';

// ==================== TIPOS PARA NAVEGACIÓN ====================
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_SUBCATEGORY = 'SET_ACTIVE_SUBCATEGORY';
export const SET_ACTIVE_ARTICLE = 'SET_ACTIVE_ARTICLE';
export const GET_SLIDER_CATEGORIES = 'GET_SLIDER_CATEGORIES';
export const GET_SLIDER_CATEGORIES_SUCCESS = 'GET_SLIDER_CATEGORIES_SUCCESS';
export const GET_SLIDER_CATEGORIES_FAIL = 'GET_SLIDER_CATEGORIES_FAIL';
// ==================== TIPOS PARA FILTROS ====================
export const GET_FILTER_OPTIONS = 'GET_FILTER_OPTIONS';
export const GET_FILTER_OPTIONS_SUCCESS = 'GET_FILTER_OPTIONS_SUCCESS';
export const GET_FILTER_OPTIONS_FAIL = 'GET_FILTER_OPTIONS_FAIL';
// 📂 redux/constants/categoryConstants.js

// ... tus constantes existentes ...

// ==================== NUEVAS CONSTANTES PARA METADATA ====================
export const GET_CATEGORY_METADATA = 'GET_CATEGORY_METADATA';
export const GET_CATEGORY_METADATA_SUCCESS = 'GET_CATEGORY_METADATA_SUCCESS';
export const GET_CATEGORY_METADATA_FAIL = 'GET_CATEGORY_METADATA_FAIL';
// ==================== TIPOS PARA ESTADO GENERAL ====================
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_CATEGORY_STATE = 'RESET_CATEGORY_STATE';
export const CATEGORY_RESET_POSTS = 'CATEGORY_RESET_POSTS';

// ==================== TIPOS PARA CATEGORÍAS PRINCIPALES ====================
export const GET_MAIN_CATEGORIES = 'GET_MAIN_CATEGORIES';
export const GET_HIERARCHICAL_CATEGORIES = 'GET_HIERARCHICAL_CATEGORIES';

// ==================== TIPOS PARA POSTS RECIENTES ====================
export const GET_RECENT_POSTS = 'GET_RECENT_POSTS';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';
export const GET_RECENT_POSTS_FAIL = 'GET_RECENT_POSTS_FAIL';